ARG BASE_IMAGE=br:fm

FROM $BASE_IMAGE

ENV LOCAL_PREFIX=/home/coq/.local

RUN \
  --mount=type=bind,target=/home/coq/fm-artifact.zip,source=files/fm-artifact.zip \
  unzip -q -d fm-artifact fm-artifact.zip \
  && find fm-artifact/fm-install -name dune-package \
    | xargs sed -i "s|/builds/bedrocksystems/formal-methods/fm-ci/fm-install/|$LOCAL_PREFIX/|"  \
  && rsync -r fm-artifact/fm-install/ .local/ \
  && rm -rf swipl bin fm-artifact

ENV OCAMLPATH=$LOCAL_PREFIX/lib
ENV ROCQ_LIB=$OCAMLPATH/coq
ENV ROCQPATH=$ROCQ_LIB/user-contrib

COPY files/LICENSE /home/coq/LICENSE
COPY files/dune-config /home/coq/.config/dune/config

COPY files/fmdocs_python_deps.txt /tmp/files/fmdocs_python_deps.txt
RUN pip3 install -r /tmp/files/fmdocs_python_deps.txt
