ARG BASE_IMAGE=br:fm

FROM $BASE_IMAGE

COPY files/fm-artifact.zip /home/coq/fm-artifact.zip

ENV LOCAL_PREFIX=/home/coq/.local

RUN unzip -q -d fm-artifact fm-artifact.zip
RUN find fm-artifact/fm-install -name dune-package \
  | xargs sed -i "s|/builds/bedrocksystems/formal-methods/fm-ci/fm-install/|$LOCAL_PREFIX/|"
RUN rsync -r fm-artifact/fm-install/ .local/
RUN rm -rf swipl bin fm-artifact fm-artifact.zip

ENV OCAMLPATH=$LOCAL_PREFIX/lib
ENV COQ_LIB=$OCAMLPATH/coq
ENV COQPATH=$COQ_LIB/user-contrib
